### ISSUE TITLE
Update Data

### ISSUE THREAD

**Issue by garrett-huggins** [garrett-huggins/slanted.dev#1]
### Reason
Make it easier to add or remove data in the future.

### Method
Currently all data on the home page is hard-coded, update the components to render an array of their respective data.

### Tasks
- [ ] Update projects to use data
- [ ] Update recent posts to use data
- [ ] Update all social contacts to use data
